apiVersion: v1
kind: Service
metadata:
  name: threat-hunting-api
  namespace: threat-hunting
  labels:
    app: threat-hunting-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: threat-hunting-api
---
apiVersion: v1
kind: Service
metadata:
  name: threat-hunting-api-headless
  namespace: threat-hunting
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8000
  selector:
    app: threat-hunting-api
